version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_merchant
    ports:
      - "3307:3306"
    volumes:
      - "./merchants-table.sql:/docker-entrypoint-initdb.d/1.sql" 
 
